name: HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  validate:
    name: HACS repository requirements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: hacs/action@main
        with:
          category: integration
