name: Hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  validate:
    name: Manifest, translations and structure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: home-assistant/actions/hassfest@master
